stages:
  - build
  - style
  - tests
  - deploy

build_job:
  stage: build
  script: 
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  after_script:
    - chmod +x tg_notifications.sh
    - bash tg_notifications.sh

check_code_style_job:
  stage: style
  script:
    - cd src/cat
    - chmod +x style_test.sh
    - bash style_test.sh
    - make check
    - cd ../grep
    - chmod +x style_test.sh
    - bash style_test.sh
    - make check
  allow_failure: false
  after_script:
    - chmod +x tg_notifications.sh
    - bash tg_notifications.sh

tests_job:
  stage: tests
  script:
    - cd src/cat
    - make test
    - chmod +x fnc_test.sh
    - bash fnc_test.sh
    - cd ../grep
    - make test
    - chmod +x fnc_test.sh
    - bash fnc_test.sh
  allow_failure: false
  after_script:
    - chmod +x tg_notifications.sh
    - bash tg_notifications.sh

deploy_job:
  stage: deploy
  when: manual
  script:
    - bash src/transfer.sh
  after_script:
    - chmod +x tg_notifications.sh
    - bash tg_notifications.sh